#!/usr/bin/env python3

import sys
import os
import time
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from iphone_automation import iPhoneAutomation

def liene_automation_20250808_211610():
    """Generated automation script"""
    automation = iPhoneAutomation()
    
    if not automation.focus_window():
        print("Error: Could not find iPhone Mirroring window")
        return False
    
    print("Starting automated sequence...")
    
    time.sleep(2.32)
    automation.click(538.0, 702.0, button='left')
    time.sleep(2.52)
    automation.click(567.0, 696.0, button='left')
    time.sleep(6.35)
    automation.continuous_scroll(570.0, 297.0, direction='up', duration=0.16, speed=3)
    time.sleep(1.82)
    automation.continuous_scroll(573.0, 355.0, direction='down', duration=0.2, speed=2)
    time.sleep(3.82)
    automation.continuous_scroll(580.0, 338.0, direction='up', duration=1.0, speed=3)
    time.sleep(9.70)
    automation.press_key('alt')
    automation.continuous_scroll(538.30078125, 326.59765625, direction='up', duration=1.0, speed=3)
    time.sleep(3.83)
    automation.press_key('cmd')
    automation.continuous_scroll(525.0, 422.0, direction='down', duration=0.2, speed=1)
    time.sleep(1.60)
    automation.press_key('shift')
    automation.continuous_scroll(525.0, 430.0, direction='up', duration=0.2, speed=3)
    time.sleep(2.37)
    automation.press_key('alt')
    automation.continuous_scroll(523.0, 469.0, direction='right', duration=0.2, speed=3)
    time.sleep(3.63)
    automation.click(981.0, 360.0, button='left')
    time.sleep(0.91)
    automation.click(396.0, 126.0, button='left')
    time.sleep(25.04)
    automation.click(557.0, 488.0, button='left')
    time.sleep(1.00)
    automation.click(25.0, 213.0, button='left')
    time.sleep(1.25)
    automation.press_key('down')
    time.sleep(0.92)
    automation.press_key('up')
    time.sleep(1.68)
    automation.press_key('down')
    time.sleep(0.86)
    automation.press_key('down')
    time.sleep(0.38)
    automation.press_key('down')
    time.sleep(0.20)
    automation.press_key('down')
    time.sleep(0.14)
    automation.press_key('down')
    time.sleep(0.15)
    automation.press_key('down')
    time.sleep(0.13)
    automation.press_key('down')
    time.sleep(2.40)
    automation.press_key('up')
    time.sleep(2.92)
    automation.press_key('down')
    time.sleep(0.62)
    automation.press_key('down')
    time.sleep(0.14)
    automation.press_key('down')
    time.sleep(0.15)
    automation.press_key('down')
    time.sleep(0.15)
    automation.press_key('down')
    time.sleep(0.16)
    automation.press_key('down')
    time.sleep(0.15)
    automation.press_key('down')
    time.sleep(0.16)
    automation.press_key('down')
    time.sleep(0.16)
    automation.press_key('down')
    time.sleep(0.15)
    automation.press_key('down')
    time.sleep(0.16)
    automation.press_key('down')
    time.sleep(0.17)
    automation.press_key('down')
    time.sleep(0.12)
    automation.press_key('down')
    time.sleep(0.15)
    automation.press_key('down')
    time.sleep(0.18)
    automation.press_key('down')
    time.sleep(2.51)
    automation.press_key('up')
    time.sleep(3.32)
    automation.press_key('down')
    time.sleep(2.45)
    automation.click(398.0, 128.0, button='left')
    time.sleep(0.87)
    automation.click(23.0, 206.0, button='left')
    time.sleep(4.36)
    automation.press_key('up')
    time.sleep(5.05)
    automation.press_key('down')
    time.sleep(4.84)
    automation.press_key('shift_r')
    time.sleep(1.72)
    automation.press_key('up')
    time.sleep(1.96)
    automation.press_key('down')
    time.sleep(1.71)
    automation.press_key('down')
    time.sleep(2.97)
    automation.press_key('alt')
    automation.continuous_scroll(525.0, 422.0, direction='up', duration=0.2, speed=3)
    time.sleep(77.40)
    automation.press_key('alt')
    time.sleep(0.41)
    automation.click(525.0, 422.0, button='left')
    time.sleep(1.25)
    automation.click(555.0, 492.0, button='left')
    automation.continuous_scroll(525.0, 422.0, direction='down', duration=0.2, speed=3)
    time.sleep(5.43)
    automation.continuous_scroll(539.0, 569.0, direction='up', duration=0.2, speed=3)
    time.sleep(1.80)
    automation.continuous_scroll(523.0, 579.0, direction='up', duration=1.0, speed=3)
    time.sleep(3.73)
    automation.continuous_scroll(523.0, 579.0, direction='down', duration=0.85, speed=3)
    time.sleep(3.72)
    automation.press_key('alt')
    time.sleep(8.62)
    automation.press_key('alt')
    time.sleep(4.46)
    automation.press_key('alt')
    time.sleep(4.62)
    automation.click(399.42578125, 131.48046875, button='left')
    time.sleep(3.60)
    automation.press_key('c')
    automation.continuous_scroll(523.0, 579.0, direction='up', duration=1.0, speed=3)
    
    print("Automation completed!")
    return True

if __name__ == "__main__":
    liene_automation_20250808_211610()